package com.example.cp5307_final.ui.settings

/**
 * A simple manager to handle translations for different languages in the app.
 * This makes it easy to switch between English, Chinese, and Korean.
 */
object LanguageManager {
    /**
     * Returns the translated string for a given key and language.
     * If the language or key isn't found, it defaults to English.
     */
    fun getTranslation(key: String, language: String): String {
        return translations[language]?.get(key) ?: translations["English"]?.get(key) ?: key
    }

    private val translations = mapOf(
        "English" to mapOf(
            "mission" to "MISSION",
            "mission_challenge" to "MISSION CHALLENGE",
            "exit" to "Exit",
            "mission_progress" to "MISSION PROGRESS",
            "your_decision" to "YOUR DECISION",
            "secure_choice" to "SECURE CHOICE!",
            "privacy_risk" to "PRIVACY RISK DETECTED",
            "proceed_next" to "PROCEED TO NEXT MISSION",
            "confirm_decision" to "CONFIRM DECISION",
            "mission_accomplished" to "MISSION ACCOMPLISHED",
            "completion_desc" to "Your privacy defense skills are growing. You've successfully navigated today's challenges!",
            "return_center" to "RETURN TO COMMAND CENTER",
            "statistics" to "STATISTICS",
            "privacy_journey" to "Your Privacy Journey",
            "category_perf" to "Category Performance",
            "keep_it_up" to "Keep it up!",
            "motivation_tip" to "Regular practice helps you recognize complex privacy patterns effortlessly.",
            "completed" to "Completed",
            "accuracy" to "Accuracy",
            "total_correct" to "Total Correct Answers",
            "accuracy_label" to "ACCURACY",
            "settings" to "Settings",
            "dark_mode" to "Dark Mode",
            "dark_mode_desc" to "Enable dark theme for the app",
            "high_contrast" to "High Contrast",
            "high_contrast_desc" to "Increase accessibility contrast",
            "font_size" to "Font Size",
            "daily_reminders" to "Daily Reminders",
            "daily_reminders_desc" to "Get notified to complete daily challenges",
            "reminder_time" to "Reminder Time",
            "reset_progress" to "Reset All Progress",
            "language" to "Language",
            "todays_mission" to "Today's Mission",
            "enter_mission" to "ENTER MISSION",
            "review_missions" to "Review Missions",
            "explanation" to "EXPLANATION",
            "home" to "Home",
            "stats" to "Stats",
            "lang_english" to "English",
            "lang_chinese" to "Chinese",
            "lang_korean" to "Korean",
            "size_small" to "Small",
            "size_medium" to "Medium",
            "size_large" to "Large",
            // Categories
            "cat_privacy" to "Privacy",
            "cat_security" to "Security",
            "cat_social" to "Social",
            "cat_convenience" to "Convenience",
            // Scenario 1
            "s1_title" to "Location Request",
            "s1_text" to "A weather app asks for 'Always Allow' location permission. Is this necessary?",
            "s1_c1" to "Yes, always",
            "s1_c2" to "No, only while using",
            "s1_c3" to "Never",
            "s1_c4" to "Only for GPS",
            "s1_exp" to "Weather apps typically only need your location while you are using them to provide local forecasts.",
            // Scenario 2
            "s2_title" to "Camera Access",
            "s2_text" to "A calculator app requests access to your camera. Should you allow it?",
            "s2_c1" to "Yes",
            "s2_c2" to "No",
            "s2_c3" to "Only if it's a 'smart' calculator",
            "s2_c4" to "Only on weekends",
            "s2_exp" to "A standard calculator app has no legitimate reason to access your camera.",
            // Scenario 3
            "s3_title" to "Contacts Access",
            "s3_text" to "A social media app wants to access your contacts to find friends. What's the best practice?",
            "s3_c1" to "Allow always",
            "s3_c2" to "Deny everything",
            "s3_c3" to "Only sync once and review",
            "s3_c4" to "Use a fake contact list",
            "s3_exp" to "It's best to only sync once to see who is on the platform and then revoke access if you don't need ongoing syncing.",
            // Scenario 4
            "s4_title" to "Microphone Usage",
            "s4_text" to "A voice recorder app needs microphone access. When should it have it?",
            "s4_c1" to "Always",
            "s4_c2" to "Only when using the app",
            "s4_c3" to "Only when my screen is off",
            "s4_c4" to "Only for phone calls",
            "s4_exp" to "Privacy best practices suggest only giving apps access to sensitive hardware while you are actively using the feature.",
            // Scenario 5
            "s5_title" to "Background Location",
            "s5_text" to "A fitness tracker asks for background location to map your runs. Is this valid?",
            "s5_c1" to "Yes, if you want full maps",
            "s5_c2" to "No, background is never needed",
            "s5_c3" to "Only if the app is open",
            "s5_c4" to "Only for battery optimization",
            "s5_exp" to "Fitness trackers often need background location to accurately record your path even when the screen is off or the app is in the background.",
            // Scenario 6
            "s6_title" to "File Access",
            "s6_text" to "A photo editor asks for permission to 'All Files'. Should you grant it?",
            "s6_c1" to "Yes, it needs to see all photos",
            "s6_c2" to "No, use the Photo Picker instead",
            "s6_c3" to "Only if you have many files",
            "s6_c4" to "Only for JPEG files",
            "s6_exp" to "Modern Android versions provide a Photo Picker that lets you select specific images without giving the app access to your entire storage.",
            // Scenario 7
            "s7_title" to "Calendar Access",
            "s7_text" to "A flight booking app wants to add trips to your calendar. Safe?",
            "s7_c1" to "Yes, very convenient",
            "s7_c2" to "No, it will steal your schedule",
            "s7_c3" to "Only if you use Google Calendar",
            "s7_c4" to "Only if it's an international flight",
            "s7_exp" to "This is a standard convenience feature. However, always be mindful of what other calendar data the app might be able to read.",
            // Scenario 8
            "s8_title" to "SMS Permissions",
            "s8_text" to "An online store asks for SMS permissions to 'auto-fill OTP codes'. Risk?",
            "s8_c1" to "Low risk, it's just for codes",
            "s8_c2" to "High risk, it can read all messages",
            "s8_c3" to "No risk at all",
            "s8_c4" to "Only risky on old phones",
            "s8_exp" to "Granting SMS permissions often allows the app to read *all* your messages, not just the OTP. Use the SMS Retriever API instead if possible."
        ),
        "Chinese" to mapOf(
            "mission" to "任务",
            "mission_challenge" to "任务挑战",
            "exit" to "退出",
            "mission_progress" to "任务进度",
            "your_decision" to "你的决定",
            "secure_choice" to "安全的抉择！",
            "privacy_risk" to "检测到隐私风险",
            "proceed_next" to "进入下一个任务",
            "confirm_decision" to "确认决定",
            "mission_accomplished" to "任务完成",
            "completion_desc" to "你的隐私防御技能正在提升。你已成功应对今天的挑战！",
            "return_center" to "返回指挥中心",
            "statistics" to "统计数据",
            "privacy_journey" to "你的隐私之旅",
            "category_perf" to "各类别表现",
            "keep_it_up" to "继续保持！",
            "motivation_tip" to "定期练习能帮你轻松识别复杂的隐私模式。",
            "completed" to "已完成",
            "accuracy" to "准确率",
            "total_correct" to "正确答案总数",
            "accuracy_label" to "准确率",
            "settings" to "设置",
            "dark_mode" to "深色模式",
            "dark_mode_desc" to "为应用启用深色主题",
            "high_contrast" to "高对比度",
            "high_contrast_desc" to "增强辅助功能的对比度",
            "font_size" to "字体大小",
            "daily_reminders" to "每日提醒",
            "daily_reminders_desc" to "接收完成每日挑战的通知",
            "reminder_time" to "提醒时间",
            "reset_progress" to "重置所有进度",
            "language" to "语言",
            "todays_mission" to "今日任务",
            "enter_mission" to "开始任务",
            "review_missions" to "回顾任务",
            "explanation" to "解释",
            "home" to "主页",
            "stats" to "统计",
            "lang_english" to "英文",
            "lang_chinese" to "中文",
            "lang_korean" to "韩文",
            "size_small" to "小",
            "size_medium" to "中",
            "size_large" to "大",
            // Categories
            "cat_privacy" to "隐私",
            "cat_security" to "安全",
            "cat_social" to "社交",
            "cat_convenience" to "便利",
            // Scenario 1
            "s1_title" to "位置请求",
            "s1_text" to "天气应用请求“始终允许”位置权限。这有必要吗？",
            "s1_c1" to "是，始终允许",
            "s1_c2" to "否，仅在使用时",
            "s1_c3" to "从不",
            "s1_c4" to "仅用于 GPS",
            "s1_exp" to "天气应用通常只需要在你使用它们时提供本地预报。",
            // Scenario 2
            "s2_title" to "相机访问",
            "s2_text" to "计算器应用请求访问您的相机。您应该允许吗？",
            "s2_c1" to "是",
            "s2_c2" to "否",
            "s2_c3" to "仅当它是“智能”计算器时",
            "s2_c4" to "仅在周末",
            "s2_exp" to "标准计算器应用没有正当理由访问您的相机。",
            // Scenario 3
            "s3_title" to "联系人访问",
            "s3_text" to "社交媒体应用想要访问您的联系人以查找朋友。最佳做法是什么？",
            "s3_c1" to "始终允许",
            "s3_c2" to "拒绝一切",
            "s3_c3" to "仅同步一次并检查",
            "s3_c4" to "使用虚假联系人列表",
            "s3_exp" to "最好只同步一次，看看平台上谁在，如果您不需要持续同步，则撤销访问权限。",
            // Scenario 4
            "s4_title" to "麦克风使用",
            "s4_text" to "录音机应用需要麦克风访问权限。它应该什么时候拥有它？",
            "s4_c1" to "始终",
            "s4_c2" to "仅在使用应用时",
            "s4_c3" to "仅当我的屏幕关闭时",
            "s4_c4" to "仅用于通话",
            "s4_exp" to "隐私最佳实践建议仅在您主动使用该功能时才允许应用访问敏感硬件。",
            // Scenario 5
            "s5_title" to "后台位置",
            "s5_text" to "健身追踪器请求后台位置以绘制您的跑步地图。这有效吗？",
            "s5_c1" to "是的，如果您想要完整的地图",
            "s5_c2" to "不，永远不需要后台",
            "s5_c3" to "仅当应用打开时",
            "s5_c4" to "仅用于电池优化",
            "s5_exp" to "健身追踪器通常需要后台位置来准确记录您的路径，即使屏幕关闭或应用在后台运行。",
            // Scenario 6
            "s6_title" to "文件访问",
            "s6_text" to "照片编辑器请求“所有文件”的权限。你应该授予它吗？",
            "s6_c1" to "是的，它需要查看所有照片",
            "s6_c2" to "不，请改用照片选择器",
            "s6_c3" to "仅当您有很多文件时",
            "s6_c4" to "仅适用于 JPEG 文件",
            "s6_exp" to "现代 Android 版本提供照片选择器，让您选择特定的图像，而无需授予应用访问整个存储空间的权限。",
            // Scenario 7
            "s7_title" to "日历访问",
            "s7_text" to "航班预订应用想要将行程添加到您的日历中。安全吗？",
            "s7_c1" to "是的，非常方便",
            "s7_c2" to "不，它会窃取你的日程安排",
            "s7_c3" to "仅当您使用 Google 日历时",
            "s7_c4" to "仅当它是国际航班时",
            "s7_exp" to "这是一项标准的便利功能。但是，始终要注意应用可能读取的其他日历数据。",
            // Scenario 8
            "s8_title" to "短信权限",
            "s8_text" to "在线商店请求短信权限以“自动填写 OTP 代码”。有风险吗？",
            "s8_c1" to "低风险，仅用于代码",
            "s8_c2" to "高风险，它可以读取所有消息",
            "s8_c3" to "完全没有风险",
            "s8_c4" to "仅在旧手机上有风险",
            "s8_exp" to "授予短信权限通常允许应用读取您的 *所有* 消息，而不仅仅是 OTP。如果可能，请改用 SMS Retriever API。"
        ),
        "Korean" to mapOf(
            "mission" to "미션",
            "mission_challenge" to "미션 챌린지",
            "exit" to "나가기",
            "mission_progress" to "미션 진행 상황",
            "your_decision" to "당신의 결정",
            "secure_choice" to "안전한 선택!",
            "privacy_risk" to "개인정보 위험 감지",
            "proceed_next" to "다음 미션으로 진행",
            "confirm_decision" to "결정 확인",
            "mission_accomplished" to "미션 완료",
            "completion_desc" to "당신의 개인정보 보호 기술이 향상되고 있습니다. 오늘의 챌린지를 성공적으로 마쳤습니다!",
            "return_center" to "지휘 센터로 돌아가기",
            "statistics" to "통계",
            "privacy_journey" to "당신의 개인정보 여정",
            "category_perf" to "카테고리별 성과",
            "keep_it_up" to "계속 정진하세요!",
            "motivation_tip" to "정기적인 연습은 복잡한 개인정보 보호 패턴을 쉽게 인식하도록 도와줍니다.",
            "completed" to "완료됨",
            "accuracy" to "정확도",
            "total_correct" to "총 정답 수",
            "accuracy_label" to "정확도",
            "settings" to "설정",
            "dark_mode" to "다크 모드",
            "dark_mode_desc" to "앱에 다크 테마 적용",
            "high_contrast" to "고대비",
            "high_contrast_desc" to "접근성 대비 향상",
            "font_size" to "글꼴 크기",
            "daily_reminders" to "일일 알림",
            "daily_reminders_desc" to "일일 챌린지 완료 알림 받기",
            "reminder_time" to "알림 시간",
            "reset_progress" to "모든 진행 상황 초기화",
            "language" to "언어",
            "todays_mission" to "오늘의 미션",
            "enter_mission" to "미션 시작",
            "review_missions" to "미션 검토",
            "explanation" to "설명",
            "home" to "홈",
            "stats" to "통계",
            "lang_english" to "영어",
            "lang_chinese" to "중국어",
            "lang_korean" to "한국어",
            "size_small" to "작게",
            "size_medium" to "보통",
            "size_large" to "크게",
            // Categories
            "cat_privacy" to "개인정보",
            "cat_security" to "보안",
            "cat_social" to "소셜",
            "cat_convenience" to "편의",
            // Scenario 1
            "s1_title" to "위치 요청",
            "s1_text" to "날씨 앱이 '항상 허용' 위치 권한을 요청합니다. 이것이 필요할까요?",
            "s1_c1" to "네, 항상",
            "s1_c2" to "아니요, 사용하는 동안만",
            "s1_c3" to "안 함",
            "s1_c4" to "GPS 전용",
            "s1_exp" to "날씨 앱은 일반적으로 지역 예보를 제공하기 위해 앱을 사용하는 동안에만 위치 정보가 필요합니다.",
            // Scenario 2
            "s2_title" to "카메라 액세스",
            "s2_text" to "계산기 앱이 카메라 액세스 권한을 요청합니다. 허용해야 할까요?",
            "s2_c1" to "네",
            "s2_c2" to "아니요",
            "s2_c3" to "'스마트' 계산기인 경우에만",
            "s2_c4" to "주말에만",
            "s2_exp" to "표준 계산기 앱은 카메라에 액세스할 정당한 이유가 없습니다.",
            // Scenario 3
            "s3_title" to "연락처 액세스",
            "s3_text" to "소셜 미디어 앱이 친구를 찾기 위해 연락처 액세스를 원합니다. 가장 좋은 방법은 무엇일까요?",
            "s3_c1" to "항상 허용",
            "s3_c2" to "모두 거부",
            "s3_c3" to "한 번만 동기화하고 검토",
            "s3_c4" to "가짜 연락처 목록 사용",
            "s3_exp" to "플랫폼에 누가 있는지 확인하기 위해 한 번만 동기화한 다음, 지속적인 동기화가 필요하지 않으면 액세스 권한을 취소하는 것이 가장 좋습니다.",
            // Scenario 4
            "s4_title" to "마이크 사용",
            "s4_text" to "음성 녹음기 앱에 마이크 액세스 권한이 필요합니다. 언제 권한을 가져야 할까요?",
            "s4_c1" to "항상",
            "s4_c2" to "앱을 사용할 때만",
            "s4_c3" to "화면이 꺼져 있을 때만",
            "s4_c4" to "전화 통화 시에만",
            "s4_exp" to "개인정보 보호 모범 사례에 따르면 해당 기능을 활발하게 사용하는 동안에만 앱이 민감한 하드웨어에 액세스하도록 허용하는 것이 좋습니다.",
            // Scenario 5
            "s5_title" to "백그라운드 위치",
            "s5_text" to "피트니스 트래커가 달리기 경로를 지도에 표시하기 위해 백그라운드 위치를 요청합니다. 이것이 타당할까요?",
            "s5_c1" to "네, 전체 지도를 원하는 경우",
            "s5_c2" to "아니요, 백그라운드는 필요하지 않습니다",
            "s5_c3" to "앱이 열려 있을 때만",
            "s5_c4" to "배터리 최적화 시에만",
            "s5_exp" to "피트니스 트래커는 화면이 꺼져 있거나 앱이 백그라운드에 있을 때도 경로를 정확하게 기록하기 위해 백그라운드 위치가 필요한 경우가 많습니다.",
            // Scenario 6
            "s6_title" to "파일 액세스",
            "s6_text" to "사진 편집기에서 '모든 파일'에 대한 권한을 요청합니다. 허용해야 할까요?",
            "s6_c1" to "네, 모든 사진을 확인해야 합니다",
            "s6_c2" to "아니요, 대신 사진 선택 도구를 사용하세요",
            "s6_c3" to "파일이 많은 경우에만",
            "s6_c4" to "JPEG 파일에 대해서만",
            "s6_exp" to "최신 Android 버전은 앱에 전체 저장소 액세스 권한을 주지 않고도 특정 이미지를 선택할 수 있는 사진 선택 도구를 제공합니다.",
            // Scenario 7
            "s7_title" to "캘린더 액세스",
            "s7_text" to "항공권 예약 앱에서 캘린더에 일정을 추가하려고 합니다. 안전할까요?",
            "s7_c1" to "네, 매우 편리합니다",
            "s7_c2" to "아니요, 일정을 훔쳐갈 것입니다",
            "s7_c3" to "Google 캘린더를 사용하는 경우에만",
            "s7_c4" to "국제선인 경우에만",
            "s7_exp" to "이것은 표준적인 편의 기능입니다. 하지만 앱이 읽을 수 있는 다른 캘린더 데이터에 항상 유의하세요.",
            // Scenario 8
            "s8_title" to "SMS 권한",
            "s8_text" to "온라인 쇼핑몰에서 'OTP 코드 자동 입력'을 위해 SMS 권한을 요청합니다. 위험할까요?",
            "s8_c1" to "낮은 위험, 코드 전용입니다",
            "s8_c2" to "높은 위험, 모든 메시지를 읽을 수 있습니다",
            "s8_c3" to "전혀 위험하지 않음",
            "s8_c4" to "오래된 휴대폰에서만 위험함",
            "s8_exp" to "SMS 권한을 허용하면 앱이 OTP뿐만 아니라 *모든* 메시지를 읽을 수 있는 경우가 많습니다. 가능하면 대신 SMS Retriever API를 사용하세요."
        )
    )
}
