package com.example.cp5307_final.ui.settings

object LanguageManager {
    fun getTranslation(key: String, language: String): String {
        return translations[language]?.get(key) ?: translations["English"]?.get(key) ?: key
    }

    private val translations = mapOf(
        "English" to mapOf(
            "mission_challenge" to "MISSION CHALLENGE",
            "exit" to "Exit",
            "mission_progress" to "MISSION PROGRESS",
            "your_decision" to "YOUR DECISION",
            "secure_choice" to "SECURE CHOICE!",
            "privacy_risk" to "PRIVACY RISK DETECTED",
            "proceed_next" to "PROCEED TO NEXT MISSION",
            "confirm_decision" to "CONFIRM DECISION",
            "mission_accomplished" to "MISSION ACCOMPLISHED",
            "completion_desc" to "Your privacy defense skills are growing. You've successfully navigated today's challenges!",
            "return_center" to "RETURN TO COMMAND CENTER",
            "statistics" to "STATISTICS",
            "privacy_journey" to "Your Privacy Journey",
            "category_perf" to "Category Performance",
            "keep_it_up" to "Keep it up!",
            "motivation_tip" to "Regular practice helps you recognize complex privacy patterns effortlessly.",
            "completed" to "Completed",
            "accuracy" to "Accuracy",
            "total_correct" to "Total Correct Answers",
            "accuracy_label" to "ACCURACY",
            "settings" to "Settings",
            "dark_mode" to "Dark Mode",
            "dark_mode_desc" to "Enable dark theme for the app",
            "high_contrast" to "High Contrast",
            "high_contrast_desc" to "Increase accessibility contrast",
            "font_size" to "Font Size",
            "daily_reminders" to "Daily Reminders",
            "daily_reminders_desc" to "Get notified to complete daily challenges",
            "reminder_time" to "Reminder Time",
            "reset_progress" to "Reset All Progress",
            "language" to "Language",
            "todays_mission" to "Today's Mission",
            "enter_mission" to "ENTER MISSION",
            "review_missions" to "Review Missions",
            "explanation" to "EXPLANATION",
            "home" to "Home",
            "stats" to "Stats"
        ),
        "Mandarin Chinese" to mapOf(
            "mission_challenge" to "任务挑战",
            "exit" to "退出",
            "mission_progress" to "任务进度",
            "your_decision" to "你的决定",
            "secure_choice" to "安全的抉择！",
            "privacy_risk" to "检测到隐私风险",
            "proceed_next" to "进入下一个任务",
            "confirm_decision" to "确认决定",
            "mission_accomplished" to "任务完成",
            "completion_desc" to "你的隐私防御技能正在提升。你已成功应对今天的挑战！",
            "return_center" to "返回指挥中心",
            "statistics" to "统计数据",
            "privacy_journey" to "你的隐私之旅",
            "category_perf" to "各类别表现",
            "keep_it_up" to "继续保持！",
            "motivation_tip" to "定期练习能帮你轻松识别复杂的隐私模式。",
            "completed" to "已完成",
            "accuracy" to "准确率",
            "total_correct" to "正确答案总数",
            "accuracy_label" to "准确率",
            "settings" to "设置",
            "dark_mode" to "深色模式",
            "dark_mode_desc" to "为应用启用深色主题",
            "high_contrast" to "高对比度",
            "high_contrast_desc" to "增强辅助功能的对比度",
            "font_size" to "字体大小",
            "daily_reminders" to "每日提醒",
            "daily_reminders_desc" to "接收完成每日挑战的通知",
            "reminder_time" to "提醒时间",
            "reset_progress" to "重置所有进度",
            "language" to "语言",
            "todays_mission" to "今日任务",
            "enter_mission" to "开始任务",
            "review_missions" to "回顾任务",
            "explanation" to "解释",
            "home" to "主页",
            "stats" to "统计"
        ),
        "Korean" to mapOf(
            "mission_challenge" to "미션 챌린지",
            "exit" to "나가기",
            "mission_progress" to "미션 진행 상황",
            "your_decision" to "당신의 결정",
            "secure_choice" to "안전한 선택!",
            "privacy_risk" to "개인정보 위험 감지",
            "proceed_next" to "다음 미션으로 진행",
            "confirm_decision" to "결정 확인",
            "mission_accomplished" to "미션 완료",
            "completion_desc" to "당신의 개인정보 보호 기술이 향상되고 있습니다. 오늘의 챌린지를 성공적으로 마쳤습니다!",
            "return_center" to "지휘 센터로 돌아가기",
            "statistics" to "통계",
            "privacy_journey" to "당신의 개인정보 여정",
            "category_perf" to "카테고리별 성과",
            "keep_it_up" to "계속 정진하세요!",
            "motivation_tip" to "정기적인 연습은 복잡한 개인정보 보호 패턴을 쉽게 인식하도록 도와줍니다.",
            "completed" to "완료됨",
            "accuracy" to "정확도",
            "total_correct" to "총 정답 수",
            "accuracy_label" to "정확도",
            "settings" to "설정",
            "dark_mode" to "다크 모드",
            "dark_mode_desc" to "앱에 다크 테마 적용",
            "high_contrast" to "고대비",
            "high_contrast_desc" to "접근성 대비 향상",
            "font_size" to "글꼴 크기",
            "daily_reminders" to "일일 알림",
            "daily_reminders_desc" to "일일 챌린지 완료 알림 받기",
            "reminder_time" to "알림 시간",
            "reset_progress" to "모든 진행 상황 초기화",
            "language" to "언어",
            "todays_mission" to "오늘의 미션",
            "enter_mission" to "미션 시작",
            "review_missions" to "미션 검토",
            "explanation" to "설명",
            "home" to "홈",
            "stats" to "통계"
        )
    )
}
