package com.example.cp5307_final.ui.settings

/**
 * A simple manager to handle translations for different languages in the app.
 * This makes it easy to switch between English, Chinese, and Korean.
 */
object LanguageManager {
    /**
     * Returns the translated string for a given key and language.
     * If the language or key isn't found, it defaults to English.
     */
    fun getTranslation(key: String, language: String): String {
        return translations[language]?.get(key) ?: translations["English"]?.get(key) ?: key
    }

    private val translations = mapOf(
        "English" to mapOf(
            "mission" to "MISSION",
            "mission_challenge" to "MISSION CHALLENGE",
            "exit" to "Exit",
            "mission_progress" to "MISSION PROGRESS",
            "your_decision" to "YOUR DECISION",
            "secure_choice" to "SECURE CHOICE!",
            "privacy_risk" to "PRIVACY RISK DETECTED",
            "proceed_next" to "PROCEED TO NEXT MISSION",
            "confirm_decision" to "CONFIRM DECISION",
            "mission_accomplished" to "MISSION ACCOMPLISHED",
            "completion_desc" to "Your privacy defense skills are growing. You've successfully navigated today's challenges!",
            "return_center" to "RETURN TO COMMAND CENTER",
            "statistics" to "STATISTICS",
            "privacy_journey" to "Your Privacy Journey",
            "category_perf" to "Category Performance",
            "keep_it_up" to "Keep it up!",
            "motivation_tip" to "Regular practice helps you recognize complex privacy patterns effortlessly.",
            "completed" to "Completed",
            "accuracy" to "Accuracy",
            "total_correct" to "Total Correct Answers",
            "accuracy_label" to "ACCURACY",
            "settings" to "Settings",
            "dark_mode" to "Dark Mode",
            "dark_mode_desc" to "Enable dark theme for the app",
            "high_contrast" to "High Contrast",
            "high_contrast_desc" to "Increase accessibility contrast",
            "font_size" to "Font Size",
            "daily_reminders" to "Daily Reminders",
            "daily_reminders_desc" to "Get notified to complete daily challenges",
            "reminder_time" to "Reminder Time",
            "reset_progress" to "Reset All Progress",
            "language" to "Language",
            "todays_mission" to "Today's Mission",
            "enter_mission" to "ENTER MISSION",
            "review_missions" to "Review Missions",
            "explanation" to "EXPLANATION",
            "home" to "Home",
            "stats" to "Stats",
            "lang_english" to "English",
            "lang_chinese" to "Chinese",
            "lang_korean" to "Korean",
            "size_small" to "Small",
            "size_medium" to "Medium",
            "size_large" to "Large",
            "mission_loading" to "Your next mission is being prepared...",
            // Categories
            "cat_privacy" to "Privacy",
            "cat_security" to "Security",
            "cat_social" to "Social",
            "cat_convenience" to "Convenience",
            // Scenario 1
            "s1_title" to "Location Request",
            "s1_text" to "A weather app asks for 'Always Allow' location permission. Is this necessary?",
            "s1_c1" to "Yes, always",
            "s1_c2" to "No, only while using",
            "s1_c3" to "Never",
            "s1_c4" to "Only for GPS",
            "s1_exp" to "Weather apps typically only need your location while you are using them to provide local forecasts.",
            // Scenario 2
            "s2_title" to "Camera Access",
            "s2_text" to "A calculator app requests access to your camera. Should you allow it?",
            "s2_c1" to "Yes",
            "s2_c2" to "No",
            "s2_c3" to "Only if it's a 'smart' calculator",
            "s2_c4" to "Only on weekends",
            "s2_exp" to "A standard calculator app has no legitimate reason to access your camera.",
            // Scenario 3
            "s3_title" to "Contacts Access",
            "s3_text" to "A social media app wants to access your contacts to find friends. What's the best practice?",
            "s3_c1" to "Allow always",
            "s3_c2" to "Deny everything",
            "s3_c3" to "Only sync once and review",
            "s3_c4" to "Use a fake contact list",
            "s3_exp" to "It's best to only sync once to see who is on the platform and then revoke access if you don't need ongoing syncing.",
            // Scenario 4
            "s4_title" to "Microphone Usage",
            "s4_text" to "A voice recorder app needs microphone access. When should it have it?",
            "s4_c1" to "Always",
            "s4_c2" to "Only when using the app",
            "s4_c3" to "Only when my screen is off",
            "s4_c4" to "Only for phone calls",
            "s4_exp" to "Privacy best practices suggest only giving apps access to sensitive hardware while you are actively using the feature.",
            // Scenario 5
            "s5_title" to "Background Location",
            "s5_text" to "A fitness tracker asks for background location to map your runs. Is this valid?",
            "s5_c1" to "Yes, if you want full maps",
            "s5_c2" to "No, background is never needed",
            "s5_c3" to "Only if the app is open",
            "s5_c4" to "Only for battery optimization",
            "s5_exp" to "Fitness trackers often need background location to accurately record your path even when the screen is off or the app is in the background.",
            // Scenario 6
            "s6_title" to "File Access",
            "s6_text" to "A photo editor asks for permission to 'All Files'. Should you grant it?",
            "s6_c1" to "Yes, it needs to see all photos",
            "s6_c2" to "No, use the Photo Picker instead",
            "s6_c3" to "Only if you have many files",
            "s6_c4" to "Only for JPEG files",
            "s6_exp" to "Modern Android versions provide a Photo Picker that lets you select specific images without giving the app access to your entire storage.",
            // Scenario 7
            "s7_title" to "Calendar Access",
            "s7_text" to "A flight booking app wants to add trips to your calendar. Safe?",
            "s7_c1" to "Yes, very convenient",
            "s7_c2" to "No, it will steal your schedule",
            "s7_c3" to "Only if you use Google Calendar",
            "s7_c4" to "Only if it's an international flight",
            "s7_exp" to "This is a standard convenience feature. However, always be mindful of what other calendar data the app might be able to read.",
            // Scenario 8
            "s8_title" to "SMS Permissions",
            "s8_text" to "An online store asks for SMS permissions to 'auto-fill OTP codes'. Risk?",
            "s8_c1" to "Low risk, it's just for codes",
            "s8_c2" to "High risk, it can read all messages",
            "s8_c3" to "No risk at all",
            "s8_c4" to "Only risky on old phones",
            "s8_exp" to "Granting SMS permissions often allows the app to read *all* your messages, not just the OTP. Use the SMS Retriever API instead if possible.",
            // Scenario 9
            "s9_title" to "Flashlight Permission",
            "s9_text" to "A simple flashlight app asks for your location. Why would it need it?",
            "s9_c1" to "To light up the right area",
            "s9_c2" to "To show local ads",
            "s9_c3" to "To help find your phone",
            "s9_c4" to "It doesn't need it",
            "s9_exp" to "Many free apps collect location data to sell to advertisers. Flashlights don't need location.",
            // Scenario 10
            "s10_title" to "QR Scanner Contacts",
            "s10_text" to "A QR code scanner app asks to access your contacts after scanning a link. Should you allow?",
            "s10_c1" to "Yes, it's normal",
            "s10_c2" to "No, it's suspicious",
            "s10_c3" to "Only for business cards",
            "s10_c4" to "Only if you trust the link",
            "s10_exp" to "Scanning a link shouldn't require your entire contact list. This is likely data harvesting.",
            // Scenario 11
            "s11_title" to "Music Player Calls",
            "s11_text" to "An offline music player requests permission to 'make and manage phone calls'. Why?",
            "s11_c1" to "To sing to you",
            "s11_c2" to "To pause music during calls",
            "s11_c3" to "To record your calls",
            "s11_c4" to "To call your friends",
            "s11_exp" to "Legacy Android permissions sometimes combined 'read phone state' (to know if a call is active) with 'make calls'. Modern apps use better methods.",
            // Scenario 12
            "s12_title" to "Game Bluetooth",
            "s12_text" to "A single-player offline game asks for Bluetooth access. What is the risk?",
            "s12_c1" to "Battery drain only",
            "s12_c2" to "Location tracking via beacons",
            "s12_c3" to "No risk if no device connected",
            "s12_c4" to "Game becomes multiplayer",
            "s12_exp" to "Bluetooth can be used to scan for nearby beacons and determine your precise location without GPS.",
            // Scenario 13
            "s13_title" to "Browser Health Data",
            "s13_text" to "A web browser asks for access to your 'Physical Activity' or step count. Is this typical?",
            "s13_c1" to "Yes, for fitness sites",
            "s13_c2" to "No, browsers don't need this",
            "s13_c3" to "Only on sports websites",
            "s13_c4" to "To count your scrolling",
            "s13_exp" to "While some sites might use it for fitness features, granting it to the browser as a whole is a privacy risk for tracking.",
            // Scenario 14
            "s14_title" to "Wallpaper Microphone",
            "s14_text" to "A live wallpaper app requests microphone access. What could be the reason?",
            "s14_c2" to "To listen for commands",
            "s14_c3" to "To react to ambient sound",
            "s14_c1" to "To record your voice",
            "s14_c4" to "No valid reason",
            "s14_exp" to "Some live wallpapers change patterns based on music or sound, but it's a high privacy risk if you aren't using that feature.",
            // Scenario 15
            "s15_title" to "Antivirus Accessibility",
            "s15_text" to "An antivirus app asks for 'Accessibility Services'. Is this safe?",
            "s15_c1" to "Always safe",
            "s15_c2" to "Safe only from trusted brands",
            "s15_c3" to "Never safe",
            "s15_c4" to "Only for visually impaired",
            "s15_exp" to "Accessibility services can see everything on your screen. Only grant it to apps you absolutely trust for security scanning.",
            // Scenario 16
            "s16_title" to "Social Media Activity",
            "s16_text" to "A social media app asks for 'Physical Activity' permission. Why?",
            "s16_c1" to "To track your workouts",
            "s16_c2" to "To improve ad targeting",
            "s16_c3" to "To see if you are walking",
            "s16_c4" to "To count your steps for points",
            "s16_exp" to "Social media apps use activity data to better understand your daily habits and show more targeted advertisements.",
            // Scenario 17
            "s17_title" to "Shopping Clipboard",
            "s17_text" to "A shopping app automatically reads your clipboard when you open it. Is this okay?",
            "s17_c1" to "Yes, for discount codes",
            "s17_c2" to "No, clipboard has private info",
            "s17_c3" to "Only if it asks first",
            "s17_c4" to "Only on Android 12+",
            "s17_exp" to "The clipboard can contain passwords or private messages. Modern Android notifies you when apps read it.",
            // Scenario 18
            "s18_title" to "Video Nearby Devices",
            "s18_text" to "A video streaming app asks for 'Nearby Devices' permission. What does it do?",
            "s18_c1" to "Finds your friends",
            "s18_c2" to "Casts to your TV",
            "s18_c3" to "Steals data from PCs",
            "s18_c4" to "Connects to car audio",
            "s18_exp" to "This permission is needed to find and connect to devices like Chromecasts or smart speakers on your network.",
            // Scenario 19
            "s19_title" to "Game Overlay",
            "s19_text" to "A mobile game asks for 'Display over other apps'. Why?",
            "s19_c1" to "To show game notifications",
            "s19_c2" to "To show chat bubbles",
            "s19_c3" to "To hide the home button",
            "s19_c4" to "To record the screen",
            "s19_exp" to "While used for chat bubbles, malicious apps use this to create fake login screens over your real apps.",
            // Scenario 20
            "s20_title" to "Cleaning App Usage",
            "s20_text" to "A 'Phone Cleaner' app asks for 'Usage Access'. What can it see?",
            "s20_c1" to "Only trash files",
            "s20_c2" to "Which apps you use and when",
            "s20_c3" to "Your browser history",
            "s20_c4" to "Your private photos",
            "s20_exp" to "Usage access allows the app to track how often and for how long you use other applications.",
            // Scenario 21
            "s21_title" to "File Manager Installs",
            "s21_text" to "A third-party file manager asks to 'Install Unknown Apps'. Is this a risk?",
            "s21_c1" to "No risk at all",
            "s21_c2" to "High risk if you install APKs",
            "s21_c3" to "Only risk for old Androids",
            "s21_c4" to "Only risk on rooted phones",
            "s21_exp" to "Enabling this allows the app to install other apps that haven't been vetted by the Play Store.",
            // Scenario 22
            "s22_title" to "Notification Access",
            "s22_text" to "A 'Notification History' app needs 'Notification Access'. What's the trade-off?",
            "s22_c1" to "Better battery life",
            "s22_c2" to "It can read all message texts",
            "s22_c3" to "It can delete your emails",
            "s22_c4" to "It can reply to your calls",
            "s22_exp" to "Notification access lets an app see every notification you receive, including private 2FA codes and personal messages.",
            // Scenario 23
            "s23_title" to "Battery Optimization",
            "s23_text" to "A battery saver app asks to 'Ignore Battery Optimizations'. What happens?",
            "s23_c1" to "Phone charges faster",
            "s23_c2" to "App can run in background forever",
            "s23_c3" to "Screen becomes brighter",
            "s23_c4" to "Battery lasts longer",
            "s23_exp" to "Ignoring optimizations lets the app stay active in the background, which might actually *drain* more battery.",
            // Scenario 24
            "s24_title" to "Weather Background",
            "s24_text" to "A weather app wants 'Background Location' for 'Severe Weather Alerts'. Is this fair?",
            "s24_c1" to "Yes, to alert you where you are",
            "s24_c2" to "No, alerts don't need location",
            "s24_c3" to "Only if you travel a lot",
            "s24_c4" to "Only if you have no GPS",
            "s24_exp" to "For features like 'follow-me' alerts, the app needs to know your location even when you aren't using it."
        ),
        "Chinese" to mapOf(
            "mission" to "任务",
            "mission_challenge" to "任务挑战",
            "exit" to "退出",
            "mission_progress" to "任务进度",
            "your_decision" to "你的决定",
            "secure_choice" to "安全的抉择！",
            "privacy_risk" to "检测到隐私风险",
            "proceed_next" to "进入下一个任务",
            "confirm_decision" to "确认决定",
            "mission_accomplished" to "任务完成",
            "completion_desc" to "你的隐私防御技能正在提升。你已成功应对今天的挑战！",
            "return_center" to "返回指挥中心",
            "statistics" to "统计数据",
            "privacy_journey" to "你的隐私之旅",
            "category_perf" to "各类别表现",
            "keep_it_up" to "继续保持！",
            "motivation_tip" to "定期练习能帮你轻松识别复杂的隐私模式。",
            "completed" to "已完成",
            "accuracy" to "准确率",
            "total_correct" to "正确答案总数",
            "accuracy_label" to "准确率",
            "settings" to "设置",
            "dark_mode" to "深色模式",
            "dark_mode_desc" to "为应用启用深色主题",
            "high_contrast" to "高对比度",
            "high_contrast_desc" to "增强辅助功能的对比度",
            "font_size" to "字体大小",
            "daily_reminders" to "每日提醒",
            "daily_reminders_desc" to "接收完成每日挑战的通知",
            "reminder_time" to "提醒时间",
            "reset_progress" to "重置所有进度",
            "language" to "语言",
            "todays_mission" to "今日任务",
            "enter_mission" to "开始任务",
            "review_missions" to "回顾任务",
            "explanation" to "解释",
            "home" to "主页",
            "stats" to "统计",
            "lang_english" to "英文",
            "lang_chinese" to "中文",
            "lang_korean" to "韩文",
            "size_small" to "小",
            "size_medium" to "中",
            "size_large" to "大",
            "mission_loading" to "正在为您准备下一个任务...",
            // Categories
            "cat_privacy" to "隐私",
            "cat_security" to "安全",
            "cat_social" to "社交",
            "cat_convenience" to "便利",
            // Scenario 1
            "s1_title" to "位置请求",
            "s1_text" to "天气应用请求“始终允许”位置权限。这有必要吗？",
            "s1_c1" to "是，始终允许",
            "s1_c2" to "否，仅在使用时",
            "s1_c3" to "从不",
            "s1_c4" to "仅用于 GPS",
            "s1_exp" to "天气应用通常只需要在你使用它们时提供本地预报。",
            // Scenario 2
            "s2_title" to "相机访问",
            "s2_text" to "计算器应用请求访问您的相机。您应该允许吗？",
            "s2_c1" to "是",
            "s2_c2" to "否",
            "s2_c3" to "仅当它是“智能”计算器时",
            "s2_c4" to "仅在周末",
            "s2_exp" to "标准计算器应用没有正当理由访问您的相机。",
            // Scenario 3
            "s3_title" to "联系人访问",
            "s3_text" to "社交媒体应用想要访问您的联系人以查找朋友。最佳做法是什么？",
            "s3_c1" to "始终允许",
            "s3_c2" to "拒绝一切",
            "s3_c3" to "仅同步一次并检查",
            "s3_c4" to "使用虚假联系人列表",
            "s3_exp" to "最好只同步一次，看看平台上谁在，如果您不需要持续同步，则撤销访问权限。",
            // Scenario 4
            "s4_title" to "麦克风使用",
            "s4_text" to "录音机应用需要麦克风访问权限。它应该什么时候拥有它？",
            "s4_c1" to "始终",
            "s4_c2" to "仅在使用应用时",
            "s4_c3" to "仅当我的屏幕关闭时",
            "s4_c4" to "仅用于通话",
            "s4_exp" to "隐私最佳实践建议仅在您主动使用该功能时才允许应用访问敏感硬件。",
            // Scenario 5
            "s5_title" to "后台位置",
            "s5_text" to "健身追踪器请求后台位置以绘制您的跑步地图。这有效吗？",
            "s5_c1" to "是的，如果您想要完整的地图",
            "s5_c2" to "不，永远不需要后台",
            "s5_c3" to "仅当应用打开时",
            "s5_c4" to "仅用于电池优化",
            "s5_exp" to "健身追踪器通常需要后台位置来准确记录您的路径，即使屏幕关闭或应用在后台运行。",
            // Scenario 6
            "s6_title" to "文件访问",
            "s6_text" to "照片编辑器请求“所有文件”的权限。你应该授予它吗？",
            "s6_c1" to "是的，它需要查看所有照片",
            "s6_c2" to "不，请改用照片选择器",
            "s6_c3" to "仅当您有很多文件时",
            "s6_c4" to "仅适用于 JPEG 文件",
            "s6_exp" to "现代 Android 版本提供照片选择器，让您选择特定的图像，而无需授予应用访问整个存储空间的权限。",
            // Scenario 7
            "s7_title" to "日历访问",
            "s7_text" to "航班预订应用想要将行程添加到您的日历中。安全吗？",
            "s7_c1" to "是的，非常方便",
            "s7_c2" to "不，它会窃取你的日程安排",
            "s7_c3" to "仅当您使用 Google 日历时",
            "s7_c4" to "仅当它是国际航班时",
            "s7_exp" to "这是一项标准的便利功能。但是，始终要注意应用可能读取的其他日历数据。",
            // Scenario 8
            "s8_title" to "短信权限",
            "s8_text" to "在线商店请求短信权限以“自动填写 OTP 代码”。有风险吗？",
            "s8_c1" to "低风险，仅用于代码",
            "s8_c2" to "高风险，它可以读取所有消息",
            "s8_c3" to "完全没有风险",
            "s8_c4" to "仅在旧手机上有风险",
            "s8_exp" to "授予短信权限通常允许应用读取您的 *所有* 消息，而不仅仅是 OTP。如果可能，请改用 SMS Retriever API。",
            // Scenario 9
            "s9_title" to "手电筒权限",
            "s9_text" to "一个简单的手电筒应用请求您的位置。它为什么需要它？",
            "s9_c1" to "照亮正确的区域",
            "s9_c2" to "显示本地广告",
            "s9_c3" to "帮助寻找手机",
            "s9_c4" to "它不需要它",
            "s9_exp" to "许多免费应用收集位置数据以卖给广告商。手电筒不需要位置信息。",
            // Scenario 10
            "s10_title" to "二维码扫描联系人",
            "s10_text" to "二维码扫描应用在扫描链接后请求访问您的联系人。你应该允许吗？",
            "s10_c1" to "是，这很正常",
            "s10_c2" to "不，这很可疑",
            "s10_c3" to "仅用于名片",
            "s10_c4" to "仅当你信任该链接时",
            "s10_exp" to "扫描链接不需要你的整个联系人列表。这很可能是数据挖掘。",
            // Scenario 11
            "s11_title" to "音乐播放器通话",
            "s11_text" to "离线音乐播放器请求“拨打和管理电话”的权限。为什么？",
            "s11_c1" to "给你唱歌",
            "s11_c2" to "在通话时暂停音乐",
            "s11_c3" to "录制你的通话",
            "s11_c4" to "拨打你朋友的电话",
            "s11_exp" to "旧版 Android 权限有时将“读取手机状态”（以了解是否有通话）与“拨打电话”结合在一起。现代应用使用更好的方法。",
            // Scenario 12
            "s12_title" to "游戏蓝牙",
            "s12_text" to "单人离线游戏请求蓝牙访问权限。风险是什么？",
            "s12_c1" to "仅浪费电池",
            "s12_c2" to "通过信标进行位置追踪",
            "s12_c3" to "如果没有设备连接则没有风险",
            "s12_c4" to "游戏变为多人游戏",
            "s12_exp" to "蓝牙可用于扫描附近的信标，并在没有 GPS 的情况下确定您的精确位置。",
            // Scenario 13
            "s13_title" to "浏览器健康数据",
            "s13_text" to "网络浏览器请求访问您的“身体活动”或步数。这典型吗？",
            "s13_c1" to "是，用于健身网站",
            "s13_c2" to "不，浏览器不需要这个",
            "s13_c3" to "仅在体育网站上",
            "s13_c4" to "计算你的滚动次数",
            "s13_exp" to "虽然某些网站可能将其用于健身功能，但将其授予整个浏览器是追踪的隐私风险。",
            // Scenario 14
            "s14_title" to "壁纸麦克风",
            "s14_text" to "动态壁纸应用请求麦克风访问权限。可能是什么原因？",
            "s14_c2" to "倾听指令",
            "s14_c3" to "对环境声音做出反应",
            "s14_c1" to "录制你的声音",
            "s14_c4" to "没有正当理由",
            "s14_exp" to "一些动态壁纸根据音乐或声音改变图案，但如果您不使用该功能，则存在很高的隐私风险。",
            // Scenario 15
            "s15_title" to "杀毒软件辅助功能",
            "s15_text" to "杀毒软件请求“辅助功能服务”。这安全吗？",
            "s15_c1" to "始终安全",
            "s15_c2" to "仅来自信任品牌才安全",
            "s15_c3" to "从不安全",
            "s15_c4" to "仅针对视力障碍者",
            "s15_exp" to "辅助功能服务可以看到屏幕上的所有内容。仅将其授予您绝对信任的应用进行安全扫描。",
            // Scenario 16
            "s16_title" to "社交媒体活动",
            "s16_text" to "社交媒体应用请求“身体活动”权限. 为什么?",
            "s16_c1" to "追踪你的锻炼",
            "s16_c2" to "改善广告投放",
            "s16_c3" to "看看你是否在走路",
            "s16_c4" to "计步以换取积分",
            "s16_exp" to "社交媒体应用利用活动数据来更好地了解您的日常习惯并展示更具针对性的广告。",
            // Scenario 17
            "s17_title" to "购物剪贴板",
            "s17_text" to "购物应用在打开时自动读取您的剪贴板. 这可以吗?",
            "s17_c1" to "是，用于折扣码",
            "s17_c2" to "不，剪贴板包含隐私信息",
            "s17_c3" to "仅当它先询问时",
            "s17_c4" to "仅在 Android 12+ 上",
            "s17_exp" to "剪贴板可能包含密码或私人消息. 现代 Android 在应用读取它时会通知您。",
            // Scenario 18
            "s18_title" to "视频附近设备",
            "s18_text" to "视频流媒体应用请求“附近设备”权限. 它有什么作用?",
            "s18_c1" to "查找你的朋友",
            "s18_c2" to "投屏到你的电视",
            "s18_c3" to "从电脑窃取数据",
            "s18_c4" to "连接到汽车音响",
            "s18_exp" to "需要此权限来查找并连接到您网络上的 Chromecast 或智能音箱等设备。",
            // Scenario 19
            "s19_title" to "游戏悬浮窗",
            "s19_text" to "移动游戏请求“在其他应用上显示”. 为什么?",
            "s19_c1" to "显示游戏通知",
            "s19_c2" to "显示聊天气泡",
            "s19_c3" to "隐藏主页按钮",
            "s19_c4" to "录制屏幕",
            "s19_exp" to "虽然用于聊天气泡，但恶意应用利用它在真实应用上创建虚假的登录界面。",
            // Scenario 20
            "s20_title" to "清理软件使用情况",
            "s20_text" to "“手机清理”应用请求“使用情况访问”. 它能看到什么?",
            "s20_c1" to "仅垃圾文件",
            "s20_c2" to "你使用哪些应用以及何时使用",
            "s20_c3" to "你的浏览器历史记录",
            "s20_c4" to "你的私人照片",
            "s20_exp" to "使用情况访问允许应用追踪您使用其他应用的频率和时长。",
            // Scenario 21
            "s21_title" to "文件管理器安装",
            "s21_text" to "第三方文件管理器请求“安装未知应用”. 这有风险吗?",
            "s21_c1" to "完全没有风险",
            "s21_c2" to "如果你安装 APK，风险很高",
            "s21_c3" to "仅旧版 Android 有风险",
            "s21_c4" to "仅在 Root 手机上有风险",
            "s21_exp" to "启用此功能允许该应用安装未经 Play 商店审核的其他应用。",
            // Scenario 22
            "s22_title" to "通知访问权限",
            "s22_text" to "“通知历史”应用需要“通知访问权限”. 代价是什么?",
            "s22_c1" to "更好的电池寿命",
            "s22_c2" to "它可以读取所有消息文本",
            "s22_c3" to "它可以删除你的电子邮件",
            "s22_c4" to "它可以回复你的电话",
            "s22_exp" to "通知访问权限允许应用查看您收到的每条通知，包括私人验证码和个人消息。",
            // Scenario 23
            "s23_title" to "电池优化",
            "s23_text" to "省电应用请求“忽略电池优化”. 会发生什么?",
            "s23_c1" to "手机充电更快",
            "s23_c2" to "应用可以在后台永久运行",
            "s23_c3" to "屏幕变得更亮",
            "s23_c4" to "电池寿命更长",
            "s23_exp" to "忽略优化允许应用在后台保持活跃，这实际上可能 *更* 耗电。",
            // Scenario 24
            "s24_title" to "天气后台",
            "s24_text" to "天气应用为了“恶劣天气警报”请求“后台位置”. 这合理吗?",
            "s24_c1" to "是，为了根据你的位置报警",
            "s24_c2" to "不，警报不需要位置",
            "s24_c3" to "仅当你经常旅行时",
            "s24_c4" to "仅当你没有 GPS 时",
            "s24_exp" to "对于“跟随我”警报等功能，即使在您不使用该应用时，它也需要知道您的位置。"
        ),
        "Korean" to mapOf(
            "mission" to "미션",
            "mission_challenge" to "미션 챌린지",
            "exit" to "나가기",
            "mission_progress" to "미션 진행 상황",
            "your_decision" to "당신의 결정",
            "secure_choice" to "안전한 선택!",
            "privacy_risk" to "개인정보 위험 감지",
            "proceed_next" to "다음 미션으로 진행",
            "confirm_decision" to "결정 확인",
            "mission_accomplished" to "미션 완료",
            "completion_desc" to "당신의 개인정보 보호 기술이 향상되고 있습니다. 오늘의 챌린지를 성공적으로 마쳤습니다!",
            "return_center" to "지휘 센터로 돌아가기",
            "statistics" to "통계",
            "privacy_journey" to "당신의 개인정보 여정",
            "category_perf" to "카테고리별 성과",
            "keep_it_up" to "계속 정진하세요!",
            "motivation_tip" to "정기적인 연습은 복잡한 개인정보 보호 패턴을 쉽게 인식하도록 도와줍니다.",
            "completed" to "완료됨",
            "accuracy" to "정확도",
            "total_correct" to "총 정답 수",
            "accuracy_label" to "정확도",
            "settings" to "설정",
            "dark_mode" to "다크 모드",
            "dark_mode_desc" to "앱에 다크 테마 적용",
            "high_contrast" to "고대비",
            "high_contrast_desc" to "접근성 대비 향상",
            "font_size" to "글꼴 크기",
            "daily_reminders" to "일일 알림",
            "daily_reminders_desc" to "일일 챌린지 완료 알림 받기",
            "reminder_time" to "알림 시간",
            "reset_progress" to "모든 진행 상황 초기화",
            "language" to "언어",
            "todays_mission" to "오늘의 미션",
            "enter_mission" to "미션 시작",
            "review_missions" to "미션 검토",
            "explanation" to "설명",
            "home" to "홈",
            "stats" to "통계",
            "lang_english" to "영어",
            "lang_chinese" to "중국어",
            "lang_korean" to "한국어",
            "size_small" to "작게",
            "size_medium" to "보통",
            "size_large" to "크게",
            "mission_loading" to "다음 미션을 준비 중입니다...",
            // Categories
            "cat_privacy" to "개인정보",
            "cat_security" to "보안",
            "cat_social" to "소셜",
            "cat_convenience" to "편의",
            // Scenario 1
            "s1_title" to "위치 요청",
            "s1_text" to "날씨 앱이 '항상 허용' 위치 권한을 요청합니다. 이것이 필요할까요?",
            "s1_c1" to "네, 항상",
            "s1_c2" to "아니요, 사용하는 동안만",
            "s1_c3" to "안 함",
            "s1_c4" to "GPS 전용",
            "s1_exp" to "날씨 앱은 일반적으로 지역 예보를 제공하기 위해 앱을 사용하는 동안에만 위치 정보가 필요합니다.",
            // Scenario 2
            "s2_title" to "카메라 액세스",
            "s2_text" to "계산기 앱이 카메라 액세스 권한을 요청합니다. 허용해야 할까요?",
            "s2_c1" to "네",
            "s2_c2" to "아니요",
            "s2_c3" to "'스마트' 계산기인 경우에만",
            "s2_c4" to "주말에만",
            "s2_exp" to "표준 계산기 앱은 카메라에 액세스할 정당한 이유가 없습니다.",
            // Scenario 3
            "s3_title" to "연락처 액세스",
            "s3_text" to "소셜 미디어 앱이 친구를 찾기 위해 연락처 액세스를 원합니다. 가장 좋은 방법은 무엇일까요?",
            "s3_c1" to "항상 허용",
            "s3_c2" to "모두 거부",
            "s3_c3" to "한 번만 동기화하고 검토",
            "s3_c4" to "가짜 연락처 목록 사용",
            "s3_exp" to "플랫폼에 누가 있는지 확인하기 위해 한 번만 동기화한 다음, 지속적인 동기화가 필요하지 않으면 액세스 권한을 취소하는 것이 가장 좋습니다.",
            // Scenario 4
            "s4_title" to "마이크 사용",
            "s4_text" to "음성 녹음기 앱에 마이크 액세스 권한이 필요합니다. 언제 권한을 가져야 할까요?",
            "s4_c1" to "항상",
            "s4_c2" to "앱을 사용할 때만",
            "s4_c3" to "화면이 꺼져 있을 때만",
            "s4_c4" to "전화 통화 시에만",
            "s4_exp" to "개인정보 보호 모범 사례에 따르면 해당 기능을 활발하게 사용하는 동안에만 앱이 민감한 하드웨어에 액세스하도록 허용하는 것이 좋습니다.",
            // Scenario 5
            "s5_title" to "백그라운드 위치",
            "s5_text" to "피트니스 트래커가 달리기 경로를 지도에 표시하기 위해 백그라운드 위치를 요청합니다. 이것이 타당할까요?",
            "s5_c1" to "네, 전체 지도를 원하는 경우",
            "s5_c2" to "아니요, 백그라운드는 필요하지 않습니다",
            "s5_c3" to "앱이 열려 있을 때만",
            "s5_c4" to "배터리 최적화 시에만",
            "s5_exp" to "피트니스 트래커는 화면이 꺼져 있거나 앱이 백그라운드에 있을 때도 경로를 정확하게 기록하기 위해 백그라운드 위치가 필요한 경우가 많습니다.",
            // Scenario 6
            "s6_title" to "파일 액세스",
            "s6_text" to "사진 편집기에서 '모든 파일'에 대한 권한을 요청합니다. 허용해야 할까요?",
            "s6_c1" to "네, 모든 사진을 확인해야 합니다",
            "s6_c2" to "아니요, 대신 사진 선택 도구를 사용하세요",
            "s6_c3" to "파일이 많은 경우에만",
            "s6_c4" to "JPEG 파일에 대해서만",
            "s6_exp" to "최신 Android 버전은 앱에 전체 저장소 액세스 권한을 주지 않고도 특정 이미지를 선택할 수 있는 사진 선택 도구를 제공합니다.",
            // Scenario 7
            "s7_title" to "캘린더 액세스",
            "s7_text" to "항공권 예약 앱에서 캘린더에 일정을 추가하려고 합니다. 안전할까요?",
            "s7_c1" to "네, 매우 편리합니다",
            "s7_c2" to "아니요, 일정을 훔쳐갈 것입니다",
            "s7_c3" to "Google 캘린더를 사용하는 경우에만",
            "s7_c4" to "국제선인 경우에만",
            "s7_exp" to "이것은 표준적인 편의 기능입니다. 하지만 앱이 읽을 수 있는 다른 캘린더 데이터에 항상 유의하세요.",
            // Scenario 8
            "s8_title" to "SMS 권한",
            "s8_text" to "온라인 쇼핑몰에서 'OTP 코드 자동 입력'을 위해 SMS 권한을 요청합니다. 위험할까요?",
            "s8_c1" to "낮은 위험, 코드 전용입니다",
            "s8_c2" to "높은 위험, 모든 메시지를 읽을 수 있습니다",
            "s8_c3" to "전혀 위험하지 않음",
            "s8_c4" to "오래된 휴대폰에서만 위험함",
            "s8_exp" to "SMS 권한을 허용하면 앱이 OTP뿐만 아니라 *모든* 메시지를 읽을 수 있는 경우가 많습니다. 가능하면 대신 SMS Retriever API를 사용하세요.",
            // Scenario 9
            "s9_title" to "손전등 권한",
            "s9_text" to "단순한 손전등 앱이 위치 정보를 요청합니다. 왜 필요할까요?",
            "s9_c1" to "올바른 지역을 비추기 위해",
            "s9_c2" to "지역 광고를 표시하기 위해",
            "s9_c3" to "휴대폰 찾기를 돕기 위해",
            "s9_c4" to "필요하지 않습니다",
            "s9_exp" to "많은 무료 앱들이 광고주에게 팔기 위해 위치 데이터를 수집합니다. 손전등은 위치 정보가 필요하지 않습니다.",
            // Scenario 10
            "s10_title" to "QR 스캐너 연락처",
            "s10_text" to "QR 코드 스캐너 앱이 링크 스캔 후 연락처 액세스를 요청합니다. 허용해야 할까요?",
            "s10_c1" to "네, 정상입니다",
            "s10_c2" to "아니요, 의심스럽습니다",
            "s10_c3" to "명함인 경우에만",
            "s10_c4" to "링크를 신뢰하는 경우에만",
            "s10_exp" to "링크 스캔에 전체 연락처 목록은 필요하지 않습니다. 이는 데이터 수집일 가능성이 높습니다.",
            // Scenario 11
            "s11_title" to "음악 플레이어 통화",
            "s11_text" to "오프라인 음악 플레이어가 '전화 걸기 및 관리' 권한을 요청합니다. 왜일까요?",
            "s11_c1" to "노래를 불러주기 위해",
            "s11_c2" to "통화 중 음악을 일시 정지하기 위해",
            "s11_c3" to "통화를 녹음하기 위해",
            "s11_c4" to "친구에게 전화를 걸기 위해",
            "s11_exp" to "이전 Android 권한은 때때로 '휴대폰 상태 읽기'(통화 중인지 확인)와 '전화 걸기'를 결합했습니다. 최신 앱은 더 나은 방법을 사용합니다.",
            // Scenario 12
            "s12_title" to "게임 블루투스",
            "s12_text" to "싱글 플레이어 오프라인 게임이 블루투스 액세스를 요청합니다. 위험 요소는 무엇인가요?",
            "s12_c1" to "배터리 소모만 발생",
            "s12_c2" to "비콘을 통한 위치 추적",
            "s12_c3" to "연결된 장치가 없으면 위험 없음",
            "s12_c4" to "멀티플레이어 게임으로 전환됨",
            "s12_exp" to "블루투스는 주변 비콘을 스캔하여 GPS 없이도 정확한 위치를 파악하는 데 사용될 수 있습니다.",
            // Scenario 13
            "s13_title" to "브라우저 건강 데이터",
            "s13_text" to "웹 브라우저가 '신체 활동' 또는 걸음 수 데이터 액세스를 요청합니다. 일반적인가요?",
            "s13_c1" to "네, 피트니스 사이트용으로",
            "s13_c2" to "아니요, 브라우저는 필요 없습니다",
            "s13_c3" to "스포츠 웹사이트에서만",
            "s13_c4" to "스크롤 횟수를 세기 위해",
            "s13_exp" to "일부 사이트는 피트니스 기능을 위해 사용할 수 있지만, 브라우저 전체에 권한을 주는 것은 추적에 대한 개인정보 위험입니다.",
            // Scenario 14
            "s14_title" to "배경화면 마이크",
            "s14_text" to "라이브 배경화면 앱이 마이크 액세스를 요청합니다. 이유는 무엇일까요?",
            "s14_c2" to "명령을 듣기 위해",
            "s14_c3" to "주변 소리에 반응하기 위해",
            "s14_c1" to "목소리를 녹음하기 위해",
            "s14_c4" to "타당한 이유 없음",
            "s14_exp" to "일부 라이브 배경화면은 음악이나 소리에 따라 패턴이 바뀌지만, 그 기능을 사용하지 않는다면 높은 개인정보 위험입니다.",
            // Scenario 15
            "s15_title" to "백신 앱 접근성",
            "s15_text" to "백신 앱이 '접근성 서비스'를 요청합니다. 안전할까요?",
            "s15_c1" to "항상 안전함",
            "s15_c2" to "신뢰할 수 있는 브랜드만 안전함",
            "s15_c3" to "절대 안전하지 않음",
            "s15_c4" to "시각 장애인용으로만",
            "s15_exp" to "접근성 서비스는 화면의 모든 것을 볼 수 있습니다. 보안 스캔을 위해 절대적으로 신뢰하는 앱에만 허용하세요.",
            // Scenario 16
            "s16_title" to "소셜 미디어 활동",
            "s16_text" to "소셜 미디어 앱이 '신체 활동' 권한을 요청합니다. 왜일까요?",
            "s16_c1" to "운동 추적을 위해",
            "s16_c2" to "광고 타겟팅 개선을 위해",
            "s16_c3" to "걷고 있는지 확인하기 위해",
            "s16_c4" to "포인트를 위한 걸음 수 측정",
            "s16_exp" to "소셜 미디어 앱은 활동 데이터를 사용하여 사용자의 일상 습관을 더 잘 이해하고 더 정밀한 타겟 광고를 보여줍니다.",
            // Scenario 17
            "s17_title" to "쇼핑 클립보드",
            "s17_text" to "쇼핑 앱을 열 때 자동으로 클립보드를 읽습니다. 괜찮을까요?",
            "s17_c1" to "네, 할인 코드를 위해",
            "s17_c2" to "아니요, 클립보드에 개인 정보가 있습니다",
            "s17_c3" to "먼저 물어보는 경우에만",
            "s17_c4" to "Android 12 이상에서만",
            "s17_exp" to "클립보드에는 비밀번호나 개인 메시지가 포함될 수 있습니다. 최신 Android는 앱이 이를 읽을 때 알림을 줍니다.",
            // Scenario 18
            "s18_title" to "비디오 주변 기기",
            "s18_text" to "비디오 스트리밍 앱이 '주변 기기' 권한을 요청합니다. 무엇을 하나요?",
            "s18_c1" to "친구 찾기",
            "s18_c2" to "TV로 전송",
            "s18_c3" to "PC에서 데이터 탈취",
            "s18_c4" to "카 오디오 연결",
            "s18_exp" to "이 권한은 네트워크에서 크롬캐스트나 스마트 스피커와 같은 기기를 찾아 연결하는 데 필요합니다.",
            // Scenario 19
            "s19_title" to "게임 오버레이",
            "s19_text" to "모바일 게임이 '다른 앱 위에 표시' 권한을 요청합니다. 왜일까요?",
            "s19_c1" to "게임 알림 표시를 위해",
            "s19_c2" to "채팅 버블 표시를 위해",
            "s19_c3" to "홈 버튼을 숨기기 위해",
            "s19_c4" to "화면 녹화를 위해",
            "s19_exp" to "채팅 버블에 사용되기도 하지만, 악성 앱은 이를 사용해 실제 앱 위에 가짜 로그인 화면을 만듭니다.",
            // Scenario 20
            "s20_title" to "클리너 앱 사용 정보",
            "s20_text" to "'폰 클리너' 앱이 '사용 정보 액세스'를 요청합니다. 무엇을 볼 수 있나요?",
            "s20_c1" to "쓰레기 파일만",
            "s20_c2" to "어떤 앱을 언제 사용하는지",
            "s20_c3" to "브라우저 방문 기록",
            "s20_c4" to "개인 사진",
            "s20_exp" to "사용 정보 액세스를 통해 앱은 다른 애플리케이션을 얼마나 자주, 얼마나 오래 사용하는지 추적할 수 있습니다.",
            // Scenario 21
            "s21_title" to "파일 관리자 설치",
            "s21_text" to "서드파티 파일 관리자가 '알 수 없는 앱 설치'를 요청합니다. 위험할까요?",
            "s21_c1" to "전혀 위험하지 않음",
            "s21_c2" to "APK를 설치하면 매우 위험함",
            "s21_c3" to "이전 Android 버전에서만 위험함",
            "s21_c4" to "루팅된 폰에서만 위험함",
            "s21_exp" to "이 설정을 활성화하면 앱이 Play 스토어에서 검증되지 않은 다른 앱을 설치할 수 있게 됩니다.",
            // Scenario 22
            "s22_title" to "알림 액세스",
            "s22_text" to "'알림 기록' 앱에 '알림 액세스'가 필요합니다. 어떤 위험이 있나요?",
            "s22_c1" to "더 나은 배터리 수명",
            "s22_c2" to "모든 메시지 내용을 읽을 수 있음",
            "s22_c3" to "이메일을 삭제할 수 있음",
            "s22_c4" to "전화에 응답할 수 있음",
            "s22_exp" to "알림 액세스를 통해 앱은 개인용 2단계 인증 코드와 개인 메시지를 포함하여 수신되는 모든 알림을 볼 수 있습니다.",
            // Scenario 23
            "s23_title" to "배터리 최적화",
            "s23_text" to "배터리 절약 앱이 '배터리 최적화 제외'를 요청합니다. 어떻게 되나요?",
            "s23_c1" to "휴대폰이 더 빨리 충전됨",
            "s23_c2" to "앱이 백그라운드에서 영구적으로 실행됨",
            "s23_c3" to "화면이 더 밝아짐",
            "s23_c4" to "배터리가 더 오래감",
            "s23_exp" to "최적화를 무시하면 앱이 백그라운드에서 계속 활성 상태로 유지되어 실제로는 배터리를 *더* 소모할 수 있습니다.",
            // Scenario 24
            "s24_title" to "날씨 백그라운드",
            "s24_text" to "날씨 앱이 '기상 특보'를 위해 '백그라운드 위치'를 원합니다. 타당한가요?",
            "s24_c1" to "네, 현재 위치 정보를 알려주기 위해",
            "s24_c2" to "아니요, 알림에 위치는 필요 없습니다",
            "s24_c3" to "여행을 많이 하는 경우에만",
            "s24_c4" to "GPS가 없는 경우에만",
            "s24_exp" to "'나를 따라오기' 알림과 같은 기능을 위해 앱은 사용 중이 아닐 때도 사용자의 위치를 알아야 합니다."
        )
    )
}
